// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtE2bqMTSn0erw2IhLKcgWKGdjKyvvIzA',
    appId: '1:644935579591:web:fa96c4e8ffa89973014be2',
    messagingSenderId: '644935579591',
    projectId: 'queries-practice-38094',
    authDomain: 'queries-practice-38094.firebaseapp.com',
    storageBucket: 'queries-practice-38094.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFgj7A_FxZgYDLU1SoIb0Jauk0m4J02lo',
    appId: '1:644935579591:android:0055d8b732065b88014be2',
    messagingSenderId: '644935579591',
    projectId: 'queries-practice-38094',
    storageBucket: 'queries-practice-38094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoEk-cM9NO3JCpvklsHdzRlRCalXkFiqE',
    appId: '1:644935579591:ios:62f5263fbcc1f208014be2',
    messagingSenderId: '644935579591',
    projectId: 'queries-practice-38094',
    storageBucket: 'queries-practice-38094.appspot.com',
    iosBundleId: 'com.example.firebaseQueries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoEk-cM9NO3JCpvklsHdzRlRCalXkFiqE',
    appId: '1:644935579591:ios:be75fc5cafc64d59014be2',
    messagingSenderId: '644935579591',
    projectId: 'queries-practice-38094',
    storageBucket: 'queries-practice-38094.appspot.com',
    iosBundleId: 'com.example.firebaseQueries.RunnerTests',
  );
}
